apiVersion: v1
kind: Pod
metadata:
  annotations:
    kompose.cmd: kompose convert
    kompose.version: 1.22.0 (955b78124)
  creationTimestamp: null
  labels:
    io.kompose.service: user-mention-service
  name: user-mention-service
spec:
  containers:
    - command:
        - UserMentionService
      image: yg397/social-network-microservices
      name: user-mention-service
      resources: {}
  hostname: user-mention-service
  restartPolicy: Never
status: {}
